# Generated by Django 5.0.3 on 2024-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0002_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='points',
            field=models.TextField(default=''),
        ),
    ]
