# Generated by Django 5.0.3 on 2024-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0003_subscriptionplan_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_words_per_day',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='words_generated_today',
            field=models.IntegerField(default=0),
        ),
    ]
