# Generated by Django 5.0.3 on 2024-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0004_subscriptionplan_max_words_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBloggerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('article_type', models.CharField(max_length=50)),
                ('api_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('generate_tags', models.BooleanField(default=False)),
                ('generate_excerpt', models.BooleanField(default=False)),
                ('num_sections', models.IntegerField(default=10)),
                ('num_words', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('topical', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('excerpt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WPCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
