# Generated by Django 5.0.3 on 2024-05-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0005_autobloggeroptions_generatedarticle_wpcredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoBloggerOptions',
        ),
    ]
