# Generated by Django 5.0.3 on 2024-05-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0006_delete_autobloggeroptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='words_generated_today',
            new_name='words_per_today',
        ),
    ]
