# Generated by Django 5.0.3 on 2024-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0007_rename_words_generated_today_usersubscription_words_per_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='words_generated_today',
            field=models.IntegerField(default=0),
        ),
    ]
