# Generated by Django 5.0.3 on 2024-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0008_usersubscription_words_generated_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='words_per_today',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='words_per_day',
            field=models.IntegerField(default=1000),
        ),
    ]
